kind: Service
apiVersion: v1
metadata:
  labels:
    run: cloud-sql-proxy-service
  name: cloud-sql-proxy-service
  namespace: cloud-sql-to-bq
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: cloud-sql-proxy
